### ISSUE TITLE
How to enlarge the size of system in variational_iPEPS ?

### ISSUE THREAD

**Issue by ZongkaiLiu** [wangleiphy/tensorgrad#2]
When running the code 'variational.py', with parameter d=2, D=2, chi=20, model='TFIM', it prints that the Hamiltonian is
```
tensor([[-2.0000, -0.5000, -0.5000, -0.0000],
        [-0.5000,  2.0000, -0.0000, -0.5000],
        [-0.5000, -0.0000,  2.0000, -0.5000],
        [-0.0000, -0.5000, -0.5000, -2.0000]], device='cuda:0',
       dtype=torch.float64)
```
it seems that the system only consists of two sites. How to enlarge the system to a larger size, like 10*10 ?

**Comment by wangleiphy** [comment]
This is h_ij that acting on a bond, hence two sites. 
This code treats infinite system size (iPEPS = infinite PEPS)

**Comment by navyTensor** [comment]
This code just demonstrates the principle of differentiable tensor networks, which can treat long-range interaction. This method only shows its huge advantages in infinite systems with translation symmetry. For infinite PEPS, the functional form of energy with respect to the local tensor is highly nonlinear, and derivative calculation of energy is nontrivial. At this time, our method can significantly simplify the derivative calculation. However, the functional form of energy with respect to the local tensor is quadratic since each local tensor is different for finite PEPS, and thus its derivative calculation is trivial by "digging a hole". Certainly, you can also use our method to calculate the derivative of energy for finite PEPS, but have extra memory cost.
